name: "Deplot to remote VPS by SSH"
on:
  workflow_dispatch:
jobs:
  publish:
    name: publish to github registry
    runs-on: host
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /root/nodeChat
          git pull
          npm ci
          node ./server.js